# Generated by Django 4.2 on 2024-08-13 20:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Destilado', 'Destilado'), ('Vino', 'Vino'), ('Cerveza', 'Cerveza'), ('Licor', 'Licor'), ('Espirituoso', 'Espirituoso'), ('Aperitivo', 'Aperitivo')], max_length=30)),
                ('sweetness', models.CharField(choices=[('Seco', 'Seco'), ('Semi-seco', 'Semi-seco'), ('Dulce', 'Dulce')], max_length=30)),
                ('percentage', models.CharField(choices=[('Baja graduacion', 'Baja graduación'), ('Media graduacion', 'Media graduación'), ('Alta graduacion', 'Alta graduación')], max_length=30)),
                ('tasting', models.CharField(choices=[('Para Cócteles', 'Para Cócteles'), ('Para Degustación', 'Para Degustación')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('nummber_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="El número de celular debe tener exactamente 10 numeros y comenzar con '09'.", regex='^09\\d{8}$')])),
                ('identification_card', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de cédula ecuatoriana debe tener exactamente 10 numeros.', regex='^\\d{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('amount', models.IntegerField(default=1)),
                ('picture', models.ImageField(upload_to='product_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licores.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licores.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licores.product')),
            ],
        ),
    ]
